name: hosthub_console
description: Web-only Hosthub console.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_errors:
    path: ../../../shared/libraries/app_errors
  # styled_widgets:
  #   git:
  #     url: git@github.com:Taco55/styled_widgets.git
  #     ref: v0.1.0
  styled_widgets:
    path: ../../../shared/libraries/styled_widgets
  auth_ui_flutter:
    path: ../../../shared/libraries/auth_ui_flutter

  flutter_localizations:
    sdk: flutter
  collection: ^1.19.1
  colorize: ^3.0.0
  # cupertino_icons: ^1.0.8
  dio: ^5.3.4
  equatable: ^2.0.5
  flex_color_scheme: ^8.2.0
  flutter_bloc: ^9.1.0
  flutter_localized_locales: ^2.0.5
  form_builder_validators: ^11.0.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_fonts: ^6.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.0
  talker_bloc_logger: ^5.1.9
  timeago: ^3.7.1
  toastification: ^3.0.3
  uuid: ^4.5.1
  web: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  intl_utils: ^2.8.7
  go_router_builder: ^4.1.3


flutter_intl:
  enabled: true
  class_name: S
  arb_dir: lib/shared/l10n
  output_dir: lib/shared/l10n
  use_deferred_loading: false


flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/email_templates/
    - assets/channel_images/


test:
    assets:
      - test/assets/
    sources:
      - test/helpers
