name: hosthub_console
description: Web-only Hosthub console.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_errors:
    path: ../../../shared_libraries/app_errors
  # styled_widgets:
  #   git:
  #     url: git@github.com:Taco55/styled_widgets.git
  #     ref: v0.1.0
  styled_widgets:
    path: ../../../shared_libraries/styled_widgets

  flutter_localizations:
    sdk: flutter
  animated_reorderable_list: ^1.3.0
  any_link_preview: ^3.0.3
  appflowy_board:
    git:
      url: git@github.com:AppFlowy-IO/appflowy-board.git
  avs_svg_provider: ^1.0.1
  barcode_widget: ^2.0.4
  boxy: ^2.0.9
  calendar_date_picker2: ^1.1.9
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  colorize: ^3.0.0
  crypto: ^3.0.3
  dart_quill_delta: ^10.8.1
  device_info_plus: ^10.0.1
  diacritic: ^0.1.2
  dio: ^5.3.4
  dots_indicator: ^2.1.2
  dotted_border: ^2.0.0+3
  drag_and_drop_lists: ^0.4.2
  dropdown_button2: ^2.0.0
  equatable: ^2.0.5
  figma_squircle: ^0.6.3
  file_selector: ^1.0.3
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.5
  flex_color_picker: ^3.0.2
  flex_color_scheme: ^8.2.0
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_email_sender: ^7.0.0
  flutter_form_builder: ^10.0.1
  flutter_google_places_sdk: ^0.4.2+1
  flutter_local_notifications: ^17.0.0
  flutter_localized_locales: ^2.0.5
  flutter_platform_widgets: ^8.0.0
  flutter_quill: ^11.4.1
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player: ^4.0.0+4
  flutter_slidable: ^3.0.1
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.9
  flutter_timezone: ^4.1.1
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.3.0
  form_builder_validators: ^11.0.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  go_router: ^15.1.3
  google_fonts: ^6.0.0
  google_maps_flutter: ^2.12.2
  great_list_view: ^0.2.3
  grouped_list: ^6.0.0
  horizontal_data_table: ^4.3.1
  image: ^4.5.4
  image_cropper: ^8.1.0
  image_picker: ^1.0.7
  implicitly_animated_reorderable_list_2: ^0.6.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  keyboard_actions: ^4.2.1
  loader_overlay: ^4.0.1
  location: ^8.0.0
  meta: ^1.15.0
  mime: ^2.0.0
  mobile_scanner: ^7.0.0
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.0.1
  path: ^1.9.1
  path_provider: ^2.0.11
  permission_handler: ^11.3.0
  photo_view: ^0.15.0
  provider: ^6.1.5
  reorderable_grid_view: ^2.2.5
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  sqflite: ^2.4.2
  supabase_flutter: ^2.9.0
  syncfusion_flutter_datagrid: ^27.1.52
  talker: ^5.1.9
  talker_bloc_logger: ^5.1.9
  timeago: ^3.7.1
  toastification: ^3.0.3
  trina_grid:
    git:
      url: https://github.com/doonfrs/trina_grid.git
      ref: main
  url_launcher: ^6.1.7
  uuid: ^4.5.1
  wakelock_plus: ^1.1.6
  timezone: ^0.9.0
  introduction_screen: ^3.1.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.1.5
  flutter_lints: ^5.0.0
  build_runner: 2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  intl_utils: ^2.8.7
  source_gen: ^4.1.2
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  lints: ^5.0.0
  test: ^1.26.2
  go_router_builder: ^4.1.3


flavorizr:
  ide: "vscode"
  flavors:
    dev:
      app:
        name: "HostHub Dev"
      android:
        applicationId: "com.organize.admin.dev"
      ios:
        bundleId: "com.organize.admin.dev"
    stg:
      app:
        name: "HostHub Staging"
      android:
        applicationId: "com.organize.admin.stg"
      ios:
        bundleId: "com.organize.admin.stg"
    prd:
      app:
        name: "HostHub"
      android:
        applicationId: "com.organize.admin.prd"
      ios:
      bundleId: "com.organize.admin.prd"


flutter_intl:
  enabled: true
  class_name: S
  arb_dir: lib/shared/l10n
  output_dir: lib/shared/l10n
  use_deferred_loading: false


flutter:
  generate: false
  uses-material-design: true

  fonts:
    - family: Organize Icons
      fonts:
        - asset: lib/shared/resources/fonts/organize_icons.otf
    - family: AlbertSans
      fonts:
        - asset: lib/shared/resources/fonts/AlbertSans/AlbertSans-Regular.ttf
          weight: 400
        - asset: lib/shared/resources/fonts/AlbertSans/AlbertSans-Regular.ttf
          weight: 500
        - asset: lib/shared/resources/fonts/AlbertSans/AlbertSans-SemiBold.ttf
          weight: 600
        - asset: lib/shared/resources/fonts/AlbertSans/AlbertSans-Bold.ttf
          weight: 700
  assets:
    - lib/shared/resources/assets/images/
    - lib/shared/resources/assets/images/channels/
    - assets/email_templates/
test:
    assets:
      - test/assets/
    sources:
      - test/helpers
